import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";
import { GlobalEventHandler } from "@/components/GlobalEventHandler";
import { triggerInitialization } from "@/lib/app-init";
import { UserProvider } from "@/contexts/UserContext";

// 触发应用初始化（在应用启动时自动执行）
triggerInitialization();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "造梦Ai",
  description: "Generated by create next app",
icons: {
    icon: "assets/32.png", // 指向你上传的favicon文件路径
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <GlobalEventHandler />
          <ServiceWorkerRegister />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
